# Generated by Django 3.0.3 on 2020-05-16 07:14

from django.db import migrations, models
import django.db.models.deletion
import photo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoFolderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Folder name')),
                ('description', models.TextField(verbose_name='Description of the folder')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_file', models.ImageField(upload_to=photo.models.get_path, verbose_name='Image File')),
                ('thumbnail', models.ImageField(upload_to=photo.models.get_path, verbose_name='Thumbnail File')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.PhotoFolderModel')),
            ],
        ),
    ]
