# Generated by Django 3.0.3 on 2020-05-01 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistortPhotoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='distortion/', verbose_name='Thumbnail File')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('f', models.FloatField()),
                ('k1', models.FloatField()),
                ('k2', models.FloatField()),
                ('img_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.PhotoModel')),
            ],
        ),
    ]
