# Generated by Django 3.0.3 on 2020-04-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upphoto',
            name='photo_Img',
        ),
        migrations.AddField(
            model_name='upphoto',
            name='img_file',
            field=models.ImageField(default='bla', upload_to='images/', verbose_name='Image File'),
            preserve_default=False,
        ),
    ]
