# Generated by Django 3.0.3 on 2020-05-16 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photomodel',
            name='thumbnail',
        ),
    ]
