# Generated by Django 3.0.3 on 2020-05-01 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_distortphotomodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distortphotomodel',
            old_name='thumbnail',
            new_name='distorted',
        ),
    ]
