# Generated by Django 3.0.3 on 2020-04-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20200413_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='upphoto',
            name='thumbnail',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
