# Generated by Django 3.0.3 on 2020-05-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_auto_20200501_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distortphotomodel',
            name='distorted',
            field=models.ImageField(blank=True, upload_to='distortion/', verbose_name='Thumbnail File'),
        ),
    ]
