# Generated by Django 3.0.3 on 2020-04-18 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_upphoto_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upphoto',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnails/', verbose_name='Thumbnail File'),
        ),
    ]
