# Generated by Django 3.0.3 on 2020-05-02 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_auto_20200501_1542'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DistortPhotoModel',
        ),
    ]
